{
 "title": "CNC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "device", "label": "Device Name/UUID", "query": "select name from devices" }
  ]
 },
 "panels": [
  {
   "title": "Timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "natel-discrete-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT time, value as \"Availability\"\n-- FROM history_text\nFROM get_timeline('$device', 'availability', $__from, $__to)\n-- WHERE \n--   device='$device' and\n--   path='availability' and $__timeFilter(\"time\")\n-- ORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Rotary Mode\"\nFROM get_timeline('$device', 'axes/c/rotary_mode', $__from, $__to)\n-- FROM history_text\n-- WHERE \n--   device='$device' and\n--   path='axes/c/rotary-mode' and $__timeFilter(\"time\")\n-- ORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Emergency Stop\"\nFROM get_timeline('$device', 'controller/emergency_stop', $__from, $__to)\n-- FROM history_text\n-- WHERE \n--   device='$device' and\n--   path='controller/emergency-stop' and $__timeFilter(\"time\")\n-- ORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('$device', 'controller/path/execution', $__from, $__to)\n-- FROM history_text\n-- WHERE \n--   device='$device' and\n--   path='controller/path/execution' and $__timeFilter(\"time\")\n-- ORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Controller Mode\"\nFROM get_timeline('$device', 'controller/path/controller_mode', $__from, $__to)\n-- FROM history_text\n-- WHERE \n--   device='$device' and\n--   path='controller/path/controller-mode' and $__timeFilter(\"time\")\n-- ORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "Temp/Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time, value as c\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/c/temperature' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as x\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/x/temperature' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as y\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/y/temperature' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as z\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/z/temperature' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as c2\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/c2/temperature' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as coolant\nFROM history_float\nWHERE\n  device='$device' and\n  path='systems/coolant/temperature' and\n  $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time, value as c\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/c/load' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as x\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/x/load' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as y\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/y/load' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as z\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/z/load' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as c2\nFROM history_float\nWHERE\n  device='$device' and\n  path='axes/c2/load' and\n  $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Path Feedrate (mm/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value\nFROM history_float\nWHERE\n  device='$device' and\n  path='controller/path/path_feedrate-actual' and\n  $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Spindle Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time, value as Actual\nFROM history_float\nWHERE\n  device='$device' and\n  -- path='axes/c/spindle_speed-actual' and\n  path='axes/c/rotary_velocity-actual' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as Override\nFROM history_float\nWHERE\n  -- path='axes/c/spindle-speed-override' and\n  path='controller/path/rotary_velocity_override' and\n  $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  path,\n  time,\n  value\nFROM history_all\nWHERE\n  device='$device' and\n  (path LIKE 'controller%'\n  OR path IN ('availability', 'load-condition', 'message', 'functional-mode',\n  'system-condition', 'controller/emergency-stop', 'axes/c/rotary-mode')\n  )\n  AND $__timeFilter(\"time\")\norder by time desc\nlimit 100"
      }
     ]
    }
   ]
  }
 ]
}