{
 "title": "Power Consumption",
 "tags": [ "client" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "f13_50 ",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.teximp.com/db_data/pro/nakamura_wt-wy-03/mainimg_web.jpg\"/>"
   },
   "targets": [
    { "rawSql": "SELECT 'f13_50'" }
   ]
  },
  {
   "title": "f13_50 Execution",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('f13_50', 'controller/path/execution', $__from, $__to)"
    }
   ]
  },
  {
   "title": "f13_50 Instruction",
   "type": "table",
   "gridPos": { "h": 2, "w": 18, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "select value from history_all where device='f13_50' and path='controller/path/message' order by time desc limit 1"
    }
   ]
  },
  {
   "title": "f13_50 Parts Completed",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select value from history_all where device='f13_50' and path='controller/path/part_count-complete' order by time desc limit 1"
    }
   ]
  },
  {
   "title": "f13_50 Accum Wattage GF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT ss.tt as time, sum(ss.vavg) svavg from\n(\n  SELECT time_bucket_gapfill('5 minutes', time) as tt, \n    interpolate(avg(value)) vavg\n    --sum(value) vsum, \n    --locf(sum(value)) vlocf, \n    --interpolate(sum(value)) vinterpolate\n  FROM history_float\n  WHERE\n    device='f13_50'\n    and path like 'axes/%/wattage-actual'\n    and $__timeFilter(\"time\")\n  group by tt, path\n) ss\ngroup by time\norder by 1"
    }
   ]
  },
  {
   "title": "f13_50 ttt",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('5 minutes', time) tt, path,\n    interpolate(avg(value)) vavg\n    --sum(value) vsum, \n    --locf(sum(value)) vlocf, \n    --interpolate(sum(value)) vinterpolate\n  FROM history_float\n  WHERE\n    device='f13_50'\n    and path like 'axes/%/wattage-actual'\n    and $__timeFilter(\"time\")\n  group by tt, path\n  order by 1\n"
    }
   ]
  },
  {
   "title": "f13_50 Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='f13_50'\n  and path like 'axes/%/wattage-actual'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='f13_50'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "f13_50 Wattage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='f13_50'\n  and path like 'axes/%/wattage-actual'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  },
  {
   "title": "f13_50 Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='f13_50'\n  and path like 'axes/%/load'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='f13_50'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "f13_50 Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='f13_50'\n  and path like 'axes/%/load'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  },
  {
   "title": "f13_100 Latest",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "options": {
    "content": "<img src=\"https://www.fanuc.co.jp/ja/product/robodrill/image/robodrillalphadib_cover.jpg\"/>\n           "
   },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='f13_100'\n  and path like 'axes/%/wattage-actual'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='f13_100'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "f13_100 Execution",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('f13_100', 'controller/path/execution', $__from, $__to)"
    }
   ]
  },
  {
   "title": "f13_50 Instruction",
   "type": "table",
   "gridPos": { "h": 2, "w": 18, "x": 3, "y": 43 },
   "targets": [
    {
     "rawSql": "select value from history_all where device='f13_100' and path='controller/path/message' order by time desc limit 1"
    }
   ]
  },
  {
   "title": "f13_100 Parts Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select value from history_all where device='f13_100' and path='controller/path/part_count-complete' order by time desc limit 1"
    }
   ]
  },
  {
   "title": "f13_100 Accum Wattage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT ss.tt as time, sum(ss.tv) from\n(\nSELECT time_bucket('5 minutes', time) as tt, avg(value) tv, path\nFROM history_float\nWHERE\n  device='f13_100'\n  and path like 'axes/%/wattage-actual'\n  and $__timeFilter(\"time\")\ngroup by tt, path\n) ss\ngroup by time\norder by 1"
    }
   ]
  },
  {
   "title": "f13_100 Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='f13_100'\n  and path like 'axes/%/wattage-actual'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='f13_100'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "f13_100 Wattage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='f13_100'\n  and path like 'axes/%/wattage-actual'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  },
  {
   "title": "f13_100 Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='f13_100'\n  and path like 'axes/%/load'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='f13_100'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "f13_100 Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='f13_100'\n  and path like 'axes/%/load'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  }
 ]
}